Update cell outputs
qiskit-community/platypus pull request #201
Opened 2021-11-05 13:13 UTC by frankharkins

To match new circuit colours

2021-11-05 16:43 UTC, vabarbosa approved these changes

2021-11-08 15:39 UTC, Tansito requested changes
Now the tests pass and I'm looking into this:

<img width="300" alt="Screenshot 2021-11-08 at 16 34 40" src="https://user-images.githubusercontent.com/9059044/140771128-3a4cad04-fffc-4902-899c-5d6e4be5b282.png">

2021-11-08 16:22 UTC, Tansito approved these changes

2021-11-08 16:24 UTC, vabarbosa approved these changes
thanks @frankharkins 
thanks @Tansito 
this should be good to go

2021-11-08 16:25 UTC, merged

2021-11-08 17:12 UTC, frankharkins commented
Thank you!